export const mockOrders = [
  {
    id: "1",
    invoiceNumber: "FAC-2024-001",
    date: "2024-01-15",
    status: "entregado",
    items: [
      { name: "Leche entera 1L", quantity: 2, price: 3.5 },
      { name: "Pan integral", quantity: 1, price: 2.8 },
      { name: "Huevos docena", quantity: 1, price: 4.2 },
      { name: "Manzanas rojas 1kg", quantity: 1, price: 5.9 },
    ],
    total: 19.9,
    deliveryAddress: "Av. Libertador 1234, CABA",
    paymentMethod: "Tarjeta de crédito Visa ****1234",
  },
  {
    id: "2",
    invoiceNumber: "FAC-2024-002",
    date: "2024-01-18",
    status: "pendiente",
    items: [
      { name: "Arroz integral 1kg", quantity: 1, price: 6.5 },
      { name: "Pollo entero", quantity: 1, price: 12.9 },
      { name: "Cebolla 1kg", quantity: 1, price: 2.3 },
      { name: "Tomates 1kg", quantity: 2, price: 4.8 },
      { name: "Aceite de oliva 500ml", quantity: 1, price: 8.9 },
    ],
    total: 40.2,
    deliveryAddress: "Corrientes 5678, CABA",
    paymentMethod: "Efectivo",
  },
  {
    id: "3",
    invoiceNumber: "FAC-2024-003",
    date: "2024-01-20",
    status: "entregado",
    items: [
      { name: "Yogur natural 500g", quantity: 3, price: 3.2 },
      { name: "Cereales granola", quantity: 1, price: 7.5 },
      { name: "Bananas 1kg", quantity: 1, price: 3.8 },
      { name: "Queso fresco 300g", quantity: 1, price: 6.9 },
    ],
    total: 31.0,
    deliveryAddress: "Santa Fe 9012, CABA",
    paymentMethod: "Tarjeta de débito Mastercard ****5678",
  },
  {
    id: "4",
    invoiceNumber: "FAC-2024-004",
    date: "2024-01-22",
    status: "cancelado",
    items: [
      { name: "Detergente líquido 1L", quantity: 1, price: 5.4 },
      { name: "Papel higiénico 4 rollos", quantity: 2, price: 8.9 },
      { name: "Shampoo 400ml", quantity: 1, price: 12.5 },
    ],
    total: 35.7,
    deliveryAddress: "Rivadavia 3456, CABA",
    paymentMethod: "Transferencia bancaria",
  },
  {
    id: "5",
    invoiceNumber: "FAC-2024-005",
    date: "2024-01-25",
    status: "entregado",
    items: [
      { name: "Carne molida 500g", quantity: 1, price: 8.9 },
      { name: "Pasta spaghetti 500g", quantity: 2, price: 3.2 },
      { name: "Salsa de tomate", quantity: 1, price: 4.5 },
      { name: "Queso rallado 200g", quantity: 1, price: 5.8 },
      { name: "Vino tinto 750ml", quantity: 1, price: 15.9 },
    ],
    total: 41.5,
    deliveryAddress: "Palermo 7890, CABA",
    paymentMethod: "Tarjeta de crédito American Express ****9012",
  },
  {
    id: "6",
    invoiceNumber: "FAC-2024-006",
    date: "2024-01-28",
    status: "pendiente",
    items: [
      { name: "Café molido 250g", quantity: 1, price: 9.8 },
      { name: "Azúcar 1kg", quantity: 1, price: 2.9 },
      { name: "Galletas dulces", quantity: 2, price: 4.5 },
      { name: "Mermelada de frutilla", quantity: 1, price: 6.2 },
    ],
    total: 27.9,
    deliveryAddress: "Belgrano 2345, CABA",
    paymentMethod: "Billetera virtual MercadoPago",
  },
]
