name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@main
        with:
          max_turns: 10
          direct_prompt: |
            Please review this PR efficiently. Look at the changes, provide thoughtful feedback and Focus on the most important issues on:
            - Code quality and best practices
            - Potential bugs or issues
            - Suggestions for improvements
            - Overall architecture and design decisions
            - Documentation consistency: Verify that README.md and other documentation files are updated to reflect any code changes (especially new inputs, features, or configuration options)
            
            Be constructive and specific in your feedback. Give inline comments where applicable
          anthropic_api_key: ${{ secrets.CLAUDE_AUTH_TOKEN }}
          allowed_tools: "mcp__github__create_pending_pull_request_review,mcp__github__add_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github__get_pull_request_diff"